import { useState, type FormEvent, type ReactNode } from 'react';
import { useAuth } from './AuthProvider';

export function AuthScreen(): ReactNode {
  const { signIn, signUp, continueAsDemo, error, status } = useAuth();
  const [mode, setMode] = useState<'sign_in' | 'sign_up'>('sign_in');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); try { await (mode === 'sign_in' ? signIn(email, password) : signUp(email, password)); } catch { return; } finally { setSubmitting(false); } };
  const demo = async () => { setSubmitting(true); try { await continueAsDemo(); } catch { return; } finally { setSubmitting(false); } };
  return <main className="flex min-h-screen items-center justify-center bg-background p-4"><form onSubmit={submit} className="w-full max-w-sm rounded-lg border border-border bg-surface p-6 shadow-sm"><h1 className="text-lg font-semibold text-foreground">Contact Resolution Workbench</h1><p className="mt-2 text-sm text-muted">Sign in to use an isolated workspace.</p><label className="mt-5 block text-sm text-foreground">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded border border-border bg-background px-3 py-2" /></label><label className="mt-3 block text-sm text-foreground">Password<input required minLength={6} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 w-full rounded border border-border bg-background px-3 py-2" /></label>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={submitting || status === 'bootstrapping'} className="mt-5 w-full rounded bg-accent px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{mode === 'sign_in' ? 'Sign in' : 'Create account'}</button><button type="button" onClick={() => setMode(mode === 'sign_in' ? 'sign_up' : 'sign_in')} className="mt-3 w-full text-sm text-accent">{mode === 'sign_in' ? 'Create an account' : 'Use an existing account'}</button><div className="my-4 border-t border-border" /><button type="button" onClick={demo} disabled={submitting} className="w-full rounded border border-border px-3 py-2 text-sm text-foreground disabled:opacity-50">Continue with anonymous demo</button></form></main>;
}
