from app.schemas.resolution import CaseQuery

BENCHMARK_CASES: list[dict[str, object]] = [
    {
        "case_number": "CASE-1001",
        "scenario_name": "Clean High-Confidence Match",
        "query": CaseQuery(
            name="Claire Reynolds",
            email="claire.reynolds@acmehealth.demo",
            phone="+1 202-555-0123",
            employer="Acme Health Group",
            location="Chicago, IL",
        ),
        "expected_top_score": 100,
        "expected_route": "LIKELY_MATCH",
        "has_serious_contradiction": False,
    },
    {
        "case_number": "CASE-1002",
        "scenario_name": "Stale Phone with Strong Other Evidence",
        "query": CaseQuery(
            name="David Mitchell",
            email="dmitchell@crestviewlogistics.demo",
            phone="+1 202-555-0188",
            employer="Crestview Logistics",
            location="Denver, CO",
        ),
        "expected_top_score": 75,
        "expected_route": "LIKELY_MATCH",
        "has_serious_contradiction": False,
    },
    {
        "case_number": "CASE-1003",
        "scenario_name": "Stale Email with Strong Other Evidence",
        "query": CaseQuery(
            name="Elena Rostova",
            email="elena.r@priorfirm.demo",
            phone="+1 202-555-0144",
            employer="Vanguard Analytics",
            location="Boston, MA",
        ),
        "expected_top_score": 75,
        "expected_route": "LIKELY_MATCH",
        "has_serious_contradiction": False,
    },
    {
        "case_number": "CASE-1004",
        "scenario_name": "Ambiguous Candidates (Robert Taylor)",
        "query": CaseQuery(
            name="Robert Taylor",
            email="rtaylor@summittech.demo",
            phone="+1 202-555-0177",
            employer="Summit Technologies",
            location="Seattle, WA",
        ),
        "expected_top_score": 55,
        "expected_route": "NEEDS_REVIEW",
        "has_serious_contradiction": False,
        "expected_candidate_count": 2,
    },
    {
        "case_number": "CASE-1005",
        "scenario_name": "High Score Blocked by Incompatible Suffix",
        "query": CaseQuery(
            name="Arthur James Pendelton Jr.",
            name_suffix="Jr.",
            email="a.pendelton@beacon-financial.demo",
            phone="+1 202-555-0155",
            employer="Beacon Financial",
            location="New York, NY",
        ),
        "expected_top_score": 90,
        "expected_route": "NEEDS_REVIEW",
        "has_serious_contradiction": True,
    },
    {
        "case_number": "CASE-1006",
        "scenario_name": "Conflicting Employer and Geography",
        "query": CaseQuery(
            name="Marcus Sterling",
            email="msterling@apexsupply.demo",
            phone="+1 202-555-0166",
            employer="Apex Supply Chain",
            location="Dallas, TX",
        ),
        "expected_top_score": 55,
        "expected_route": "NEEDS_REVIEW",
        "has_serious_contradiction": False,
    },
    {
        "case_number": "CASE-1007",
        "scenario_name": "Incomplete Evidence (Missing Phone and Geo)",
        "query": CaseQuery(
            name="Karen Miller",
            email="karen.m@solaris-labs.demo",
            phone=None,
            employer="Solaris Labs",
            location="Austin, TX",
        ),
        "expected_top_score": 65,
        "expected_route": "NEEDS_REVIEW",
        "has_serious_contradiction": False,
    },
    {
        "case_number": "CASE-1008",
        "scenario_name": "No Reliable Match",
        "query": CaseQuery(
            name="Tariq Al-Mansoor",
            email="tariq.m@unverified-source.demo",
            phone="+1 202-555-0199",
            employer="Independent Consulting",
            location="Phoenix, AZ",
        ),
        "expected_top_score": 10,
        "expected_route": "NO_RELIABLE_MATCH",
        "has_serious_contradiction": False,
    },
]
